### ISSUE TITLE
Bug with FT having an owner

### ISSUE THREAD

**Issue by wighawag** [loomnetwork/erc721x#14]
With the latest version, ```ownerOf`(tokenId)``` throw when called on a FT tokenId.
This is I think a sensible approach.

But the current implementation has a bug. If you transfer such FT via the standard ERC721 ```transfer``` method (without specifying quantity), the destination address to assigned to be the owner.

The result is that now the FT has an owner.

See PR : https://github.com/loomnetwork/erc721x/pull/13

**Comment by gakonst** [comment]
fixed in https://github.com/loomnetwork/erc721x/commit/81623613f31b44886588154201e3546e67e3db6b, thanks!
