### ISSUE TITLE
Does not work with openzeppelin-solidity 2.0

### ISSUE THREAD

**Issue by alexiskattan** [loomnetwork/erc721x#25]
Many of the files have been moved with openzeppelin-solidity 2.0 (AddressUtils.sol -> Address.sol, SupportsInterfaceWithLookup.sol -> ERC165.sol) which break during compiling.

**Comment by gakonst** [comment]
Yeah that's what the https://github.com/loomnetwork/erc721x/blob/master/package-lock.json#L4959 in package-lock is for. Will migrate to v2 zeppelin in the future
