### ISSUE TITLE
Doesn't compile with solc 0.4.25

### ISSUE THREAD

**Issue by jsidorenko** [loomnetwork/erc721x#26]
I would suggest changing `pragma solidity 0.4.24` to `pragma solidity ^0.4.24`, so this would support 0.4.25 version and the feature releases.
If you have concerns regarding the 0.5 version's breaking changes, then [documentation](https://solidity.readthedocs.io/en/v0.5.0/050-breaking-changes.html#interoperability-with-older-contracts) says the Solidity compiler v0.5 won't compile ^0.4.x versions

**Comment by gakonst** [comment]
Fixed in #31
