### ISSUE TITLE
tokenURI for FT

### ISSUE THREAD

**Issue by wighawag** [loomnetwork/erc721x#6]
Currently as you are probably aware your tokenURI implementation is specific to your game and cannot be used by other since it returns a specific URI linking to your domain name.

Interestingly though, you check the call by calling ```exists``` but since this function check for the owner, this forbid your FTs to have tokenURI.

This is probably not as intended.

I suggest adding the contract address as owner to FT, this way the, the function ```exists``` remain valid for both FT and NFT. 

As for the bug mentioned in https://github.com/loomnetwork/erc721x/issues/4 you could simply add a call to ```exists``` in the ```_mint``` function too

**Comment by gakonst** [comment]
Fixed in #7, thanks for the find!

**Comment by wighawag** [comment]
I would also suggest to move the current tokenURI implementation into the Card contract so the ERC721x remains independent of loom

**Comment by mattkanwisher** [comment]
@wighawag good idea I'll move the tokenURI to be abstract
